- src/common/ErrorCode.java
- src/common/ValidCheck.java
validcheck 기능 추가입니다.
나중에 검증된 값 입력할 경우 사용 하면 됩니다.
#사용방법
Validcheck 객체 생성후
validcheck.inputStringRege(validcheck.EMAIL_REGEX);
메소드 실행하면 이메일 형식에 맞춰서 입력된 문자를 반환하게 됩니다.
필요하신 정규표현식 종류 말씀해주시면 추가하여 업데이트하겠습니다.
> 250313 feat/validcheck

- src/Main.java
> PR TEST 입니다.

- Buildify_Phase-1.iml
Reverts Buildify-SSG/Buildify_Phase-1#14
> Revert "Docs 이그노어 iml파일 추가"

- Buildify_Phase-1.iml
Reverts Buildify-SSG/Buildify_Phase-1#16
> Revert "Remove tracked .iml files"

- src/MySql/LoginProcedure.sql
- src/common/ValidCheck.java
- src/domain/UserManagement/controller/LoginController.java
- src/domain/UserManagement/controller/LoginControllerImpl.java
- src/domain/UserManagement/repository/LoginRepository.java
- src/domain/UserManagement/repository/LoginRepositoryImpl.java
- src/domain/UserManagement/service/LoginService.java
- src/domain/UserManagement/service/LoginServiceImpl.java
- src/domain/UserManagement/service/test.java
- src/domain/UserManagement/service/testimp.java
- src/dto/AdminDto.java
AdminDto admindto = LoginController.getAdminLoginStatus();
- `LoginController.getAdminLoginStatus()` 실행 시,
최초 로그인한 관리자 정보를 `AdminDto` 객체에 저장합니다.
- 입고, 출고, 재고 관리 기능 구현 시, 
`AdminDto` 객체를 생성한 후 해당 메소드를 실행하면 현재 로그인된 관리자로 기능을 수행할 수 있습니다.
- TEXT Enum Class 추가 예정
- 예외처리 추가 예정
- 가능하면 콘솔에 PW입력시 비밀번호가 직접노출되지않고 *로 보이도록 구현예정
> Feature login

- src/controller/WarehouseController.java
- src/controller/WarehouseControllerImpl.java
#메인컨트롤러 일부 기능 구현
##기존 로그인 객체 선언 방법
각 컨트롤러에서 AdminDto admindto = logincontroller.getAdminLoginStatus();
하여 매번 새로운 객체를 생성해야함
-> 매번 불필요한 새로운 객체 생성을 유발하는 문제가 잇습니다.
##새로운 방법
메인컨트롤러에서 AdminDto admindto = logincontroller.getAdminLoginStatus();
객체를 생성하여 각 컨트롤러에 파라미터로 삽입합니다.
각 컨트롤러에서 메소드 실행시 파라미터로 admindto를 받으면 현재 로그인 되어있는 관리자 객체를 가져올수있습니다.
ex)
입고 관리 시스템에서
void inboundAprrove(AdminDto admindto){}
이렇게 메소드를 구현한다면 현재 로그인되어있는 관리자 정보를 불러올수있습니다.
> 250315 feature_MainController 초기 버전 기능 추가

- src/Main.java
- src/MySql/inventory_readAll_procedure.sql
- src/MySql/inventory_readOne_productName.sql
- src/MySql/sync_inventory_warehouse_trigger.sql
- src/common/ErrorCode.java
- src/common/ValidCheck.java
- src/domain/Inventory/controller/InventoryReadController.java
- src/domain/Inventory/controller/InventoryReadControllerImp.java
- src/domain/Inventory/repository/InventoryReadRepo.java
- src/domain/Inventory/repository/InventoryReadRepoImp.java
- src/domain/Inventory/service/InventoryReadService.java
- src/domain/Inventory/service/InventoryReadServiceImp.java
- src/dto/InventoryDto.java
- src/dto/WarehouseDto.java
- src/exception/InventoryException.java
- src/exception/NotFoundException.java
특정 상품명을 입력받아 재고를 조회하는 메소드입니다. 이것도 샘플 테스트 거쳤고 프로시저 적용했습니다!
> Feature inventory read one product name

- src/UserManagement/controller/SignUpController.java
- src/UserManagement/controller/SignUpControllerImpl.java
- src/UserManagement/repository/SignUpRepository.java
- src/UserManagement/repository/SignUpRepositoryImpl.java
- src/UserManagement/service/SignUpService.java
- src/UserManagement/service/SignUpServiceImpl.java
- src/common/ValidCheck.java
> ValidCheck - 회원가입 양식에 필요한 정규식 정의.

- src/Main.java
- src/MySql/inventory_read_by_clientID.sql
- src/domain/Inventory/controller/InventoryReadController.java
- src/domain/Inventory/controller/InventoryReadControllerImp.java
- src/domain/Inventory/repository/InventoryReadRepo.java
- src/domain/Inventory/repository/InventoryReadRepoImp.java
- src/domain/Inventory/service/InventoryReadService.java
- src/domain/Inventory/service/InventoryReadServiceImp.java
- src/dto/WarehouseDto.java
입점사별로 재고조회 가능하게 client_id를 입력받아 재고 조회하는 메소드 만들었고 프로시저 적용했습니다.
> readByclientID()메소드 구현

- src/MySql/LoginProcedure.sql
- src/controller/WarehouseController.java
- src/controller/WarehouseControllerImpl.java
- src/domain/UserManagement/controller/UserManagementController.java
- src/domain/UserManagement/controller/UserManagementControllerImpl.java
- src/domain/UserManagement/repository/UserManagementRepository.java
- src/domain/UserManagement/repository/UserManagementRepositoryImpl.java
- src/domain/UserManagement/service/UserManagementService.java
- src/domain/UserManagement/service/UserManagementServiceImpl.java
- src/dto/UserDto.java
- src/exception/BuildifyException.java
관리자 - 회원관리 메뉴 초기버전입니다.
SELECT,UPDATE문사용하였으며,
프로시저로 가능한 부분 리펙토링 예정입니다.
> 250316 feature_UserManagement 초기 버전 기능 추가

- src/common/ErrorCode.java
- src/common/Text.java
- src/common/ValidCheck.java
- src/controller/WarehouseControllerImpl.java
- src/domain/UserManagement/controller/UserManagementControllerImpl.java
- src/domain/UserManagement/repository/UserManagementRepositoryImpl.java
250316 ValidCheck & Enum 추가했습니다.
> 250316 ValidCheck & Enum 추가

- src/MySql/signUp.sql
- src/UserManagement/repository/SignUpRepository.java
- src/UserManagement/repository/SignUpRepositoryImpl.java
- src/UserManagement/service/SignUpService.java
- src/UserManagement/service/SignUpServiceImpl.java
- src/domain/DH_UserManagement/controller/SignUpController.java
- src/domain/DH_UserManagement/controller/SignUpControllerImpl.java
- src/domain/DH_UserManagement/repository/SignUpRepository.java
- src/domain/DH_UserManagement/repository/SignUpRepositoryImpl.java
- src/domain/DH_UserManagement/service/SignUpService.java
- src/domain/DH_UserManagement/service/SignUpServiceImpl.java
민혁님과 제가 같은폴더의 스크립트를 작업하다보니 강제로 폴더가 분리되버려서 일단 임의로 DH_UserManagement로 나누어서 작업하려고 합니다.
> Issue 폴더분기

- src/Main.java
- src/MySql/inventory_read_by_category.sql
- src/domain/Inventory/controller/InventoryDeleteContollerImp.java
- src/domain/Inventory/controller/InventoryDeleteController.java
- src/domain/Inventory/controller/InventoryReadController.java
- src/domain/Inventory/controller/InventoryReadControllerImp.java
- src/domain/Inventory/controller/InventoryUpdateController.java
- src/domain/Inventory/controller/InventoryUpdateCotrollerImp.java
- src/domain/Inventory/repository/InventoryDeleteRepo.java
- src/domain/Inventory/repository/InventoryDeleteRepoImp.java
- src/domain/Inventory/repository/InventoryReadRepo.java
- src/domain/Inventory/repository/InventoryReadRepoImp.java
- src/domain/Inventory/repository/InventoryUpdateRepo.java
- src/domain/Inventory/repository/InventoryUpdateRepoImp.java
- src/domain/Inventory/service/InventoryDeleteService.java
- src/domain/Inventory/service/InventoryDeleteServiceImp.java
- src/domain/Inventory/service/InventoryReadService.java
- src/domain/Inventory/service/InventoryReadServiceImp.java
- src/domain/Inventory/service/InventoryUpdateService.java
- src/domain/Inventory/service/InventoryUpdateServiceImp.java
- src/dto/InventoryDto.java
- src/dto/WarehouseDto.java
1. 카테고리별로 조회할 수 있게 대분류 1. pc 주요 부품, 2. 주변기기 입력 받고 그에 따라 소분류 선택해서 선택한 카테고리 DB에서 불러오게끔 메소드 정의했습니다.
2. 원래 WarehouseDTO를 썼는데 도메인 구분을 확실하게 하고 향후 확장성을 위해 inventoryDTO로 싹 변경했습니다. 결과는 동일하게 나옵니다.
3. validCheck를 최대한 적용해서 Scanner 안쓰려고 했고 나머지 클래스들도 다 정의했고 인터페이스에 메소드도 정의해놓긴 했습니다만 급하게 하느라 매개변수는 일단 신경 안쓰고 해서 추후 변경 예정입니다!
> 카테고리별 조회 메소드,validCheck 적용 및 인터페이스 정의

- src/MySql/userApprove.sql
- src/common/Text.java
- src/domain/UserManagement/controller/UserManagementControllerImpl.java
- src/domain/UserManagement/repository/UserManagementRepository.java
- src/domain/UserManagement/repository/UserManagementRepositoryImpl.java
- src/domain/UserManagement/service/UserManagementService.java
- src/domain/UserManagement/service/UserManagementServiceImpl.java
관리자가 회원 가입 요청 승인시
현재 회원에게 할당된 창고 평수 확인 후
승인 가능하도록 현재 할당된 창고 평수 확인하는 기능 추가했습니다.
> 250316 chore_회원가입 승인시 현재 회원에게 할당된 창고 평수 보여주는 기능 추가

- src/Main.java
- src/MySql/signUp.sql
- src/domain/DH_UserManagement/controller/SignUpController.java
- src/domain/DH_UserManagement/controller/SignUpControllerImpl.java
- src/domain/DH_UserManagement/repository/SignUpRepository.java
- src/domain/DH_UserManagement/repository/SignUpRepositoryImpl.java
- src/domain/DH_UserManagement/service/SignUpService.java
- src/domain/DH_UserManagement/service/SignUpServiceImpl.java
회원가입 이전에 User ID 중복 여부 검사 후 진행.
> 회원가입 시 user가 id를 입력했을 때, 이미 중복된 ID가 있는지 검출 후 회원가입 진행

- src/domain/Outbound/repository/rejectOutbound.java
- src/domain/Outbound/repository/rejectOutboundImpl.java
회원은 출고 요청을 하고 나서 관리자는 개인 사유 출고 요청 거부를 할 수 있다.
> "회원이 출고요청을 할 때 관리자는 승인거부할 수 있는 기능"

- src/Main.java
- src/domain/Inbound/controller/InboundSearchController.java
- src/domain/Inbound/controller/InboundSearchControllerImp.java
- src/domain/Inbound/repository/InboundSearchRepo.java
- src/domain/Inbound/repository/InboundSearchRepoImp.java
- src/domain/Inbound/service/InboundSearchService.java
- src/domain/Inbound/service/InboundSearchServiceImp.java
- src/dto/InboundDto.java
- src/exception/InboundException.java
> 250317 1030 입고 서치올 / 인서트하는중

- src/MySql/signUp.sql
- src/common/ValidCheck.java
- src/domain/DH_UserManagement/controller/SignUpControllerImpl.java
- src/domain/DH_UserManagement/repository/SignUpRepositoryImpl.java
- src/dto/UserDto.java
회원가입 기능 초안 제작했습니다.
아직 while문 순환 / 콘솔창에 userguide 필요합니다.
> 회원 가입 기능 초안

- src/common/ValidCheck.java
- src/domain/DH_UserManagement/controller/SignUpControllerImpl.java
> 회원가입 기능 구현 완료

- src/domain/Outbound/repository/OutboundAdminApproveRepository.java
- src/domain/Outbound/repository/OutboundAdminApproveRepositoryImpl.java
- src/domain/Outbound/service/OutboundAdminApproveService.java
- src/domain/Outbound/service/OutboundAdminApproveServiceImpl.java
회원이 출고요청을 하면 관리자가 승인을 해주는 기능입니다.
> "outboundadminapprove는 관리자가 회원이 출고요청한 것을 승인을하는 기능 "

- src/domain/DH_UserManagement/controller/FindUseridControllerImpl.java
- src/domain/DH_UserManagement/controller/UserLogin.java
- src/domain/DH_UserManagement/controller/UserLoginController.java
- src/domain/DH_UserManagement/controller/UserLoginControllerImpl.java
- src/domain/DH_UserManagement/controller/UserLoginImpl.java
- src/domain/DH_UserManagement/repository/UserLoginRepository.java
- src/domain/DH_UserManagement/repository/UserLoginRepositoryImpl.java
- src/domain/DH_UserManagement/service/UserLoginService.java
- src/domain/DH_UserManagement/service/UserLoginServiceImpl.java
유저 로그인 기능 1차 완료
추후 웨어하우스컨트롤러 통합 예정
> Feature userlogin

- src/common/Text.java
- src/controller/WarehouseController.java
- src/controller/WarehouseControllerImpl.java
유저 회원가입 / 로그인 기능 warehousecontrollerimpl에 통합
> Feature login andsignup warehousecontroller integration

- src/Main.java
- src/MySql/inventory_backupTbl_trigger.sql
- src/MySql/inventory_delete.sql
- src/domain/Inventory/controller/InventoryDeleteContollerImp.java
- src/domain/Inventory/repository/InventoryDeleteRepo.java
- src/domain/Inventory/repository/InventoryDeleteRepoImp.java
- src/domain/Inventory/service/InventoryDeleteService.java
- src/domain/Inventory/service/InventoryDeleteServiceImp.java
재고 삭제하는 메소드 구현하고 재고에서 삭제될때 삭제된 데이터 백업테이블로 옮기는 트리거랑 백업테이블 생성했습니다.
> 재고 삭제 및 백업테이블 생성&트리거 생성

- src/common/Text.java
- src/domain/UserManagement/controller/LoginControllerImpl.java
- src/domain/UserManagement/controller/UserManagementControllerImpl.java
- src/domain/UserManagement/repository/UserManagementRepositoryImpl.java
> 250317 출력문 Enum으로 변경하였습니다.

- src/domain/Outbound/repository/OutboundAdminApproveRepositoryImpl.java
- src/domain/Outbound/repository/OutboundMemberRequestRepositoryImpl.java
- src/domain/Outbound/service/OutboundAdminApproveServiceImpl.java
- src/domain/Outbound/service/OutboundMemberRequsetServiceImpl.java
Repository,Service 각각 관리자가 출고요청을 구현하는 함수,멤버가 출고를 요청하는 함수를 구현했습니다.
> "Repository,Service 각각 관리자가 출고요청을 구현하는 함수,멤버가 출고를 요청하는 함수를 구현했습니다. "

- src/MySql/LoginProcedure.sql
- src/domain/UserManagement/repository/UserManagementRepository.java
- src/domain/UserManagement/repository/UserManagementRepositoryImpl.java
- src/domain/UserManagement/service/UserManagementServiceImpl.java
UserManagementRepository select,update 문 일부 프로시저로 변경하였습니다.
> 250317 UserManagementRepository select,update 문 일부 프로시저로 변경하였습니다.

- src/Main.java
- src/domain/Inbound/controller/InboundCheckControllerImp.java
- src/domain/Inbound/repository/InboundCheckRepo.java
- src/domain/Inbound/repository/InboundCheckRepoImp.java
- src/domain/Inbound/service/InboundCheckService.java
- src/domain/Inbound/service/InboundCheckServiceImp.java
> 250318 0938 inbound 관리자 승인반려 중간피알

- src/MySql/outbound_approve.sql
- src/domain/Outbound/controller/OutboundAdminController.java
- src/domain/Outbound/controller/OutboundAdminControllerImpl.java
- src/domain/Outbound/controller/OutboundController.java
- src/domain/Outbound/repository/OutboundAdminRepository.java
- src/domain/Outbound/repository/OutboundAdminRepositoryImpl.java
- src/domain/Outbound/service/OutboundAdminService.java
- src/domain/Outbound/service/OutboundAdminServiceImpl.java
> 250318 출고관리 관리자메뉴 구현입니다.

- src/controller/WarehouseControllerImpl.java
- src/domain/DH_UserManagement/controller/UserIntegratedController.java
- src/domain/DH_UserManagement/controller/UserIntegratedControllerImpl.java
- src/domain/DH_UserManagement/controller/UserLoginController.java
- src/domain/DH_UserManagement/controller/UserLoginControllerImpl.java
회원가입 / 로그인 / 로그아웃 /  상품 정보 등록 / 모든 상품 정보 출력 / 컨트롤러 통합
> 회원가입 / 로그인 / 로그아웃 /  상품 정보 등록 / 모든 상품 정보 출력 / 컨트롤러 통합

- src/controller/WarehouseControllerImpl.java
- src/domain/UserManagement/controller/AdminController.java
> 250318 관리자 컨트롤러 구현입니다.

- src/controller/WarehouseControllerImpl.java
- src/domain/Inbound/controller/InboundController.java
- src/domain/Inbound/controller/InboundSearchControllerImp.java
- src/domain/Inbound/controller/inboundController.java
>  인바운드 통합컨트롤러 클래스정의

- src/config/Diconfig.java
- src/controller/WarehouseControllerImpl.java
250318 패키지 구조변경으로 인하여 DiConfig Import변경입니다.
> 250318 패키지 구조변경으로 인하여 DiConfig Import변경입니다.

- src/config/Diconfig.java
- src/controller/WarehouseControllerImpl.java
- src/domain/AccountManagement/User/controller/UpdateUserinfoController.java
- src/domain/AccountManagement/User/controller/UpdateUserinfoControllerImpl.java
- src/domain/AccountManagement/User/controller/UserController.java
- src/domain/AccountManagement/User/repository/UpdateUserinfoRepository.java
- src/domain/AccountManagement/User/repository/UpdateUserinfoRepositoryImpl.java
- src/domain/AccountManagement/User/service/UpdateUserinfoService.java
- src/domain/AccountManagement/User/service/UpdateUserinfoServiceImpl.java
- src/domain/Inbound/repository/InboundSearchRepoImp.java
1. 이름
2. 전화번호
3. 이메일주소
4. 주소
5. 비밀번호
변경 가능한 기능을 구현
> 유저의 선택에 따라

- src/Main.java
- src/MySql/outbound_delete.sql
- src/MySql/outbound_user_get_request.sql
- src/domain/Outbound/controller/OutboundUserController.java
- src/domain/Outbound/controller/OutboundUserControllerImpl.java
- src/domain/Outbound/repository/OutboundUserRepository.java
- src/domain/Outbound/repository/OutboundUserRepositoryImpl.java
- src/domain/Outbound/service/OutboundUserService.java
- src/domain/Outbound/service/OutboundUserServiceImpl.java
출고 회원 메뉴에서 회원이 출고 취소 요청하면 출고 리스트 중에 미승인(status=0)인값만 조회하게 해서 출고 번호 입력받아 삭제하는 메소드 구현했습니다.
> 출고 회원 취소 요청 메소드 구현

- src/MySql/outbound_approve.sql
250318 outbound_approve.sql 프로시저 변경입니다.
##변경사항
출고 관리자 승인시 재고에서 차감되게 변경하였습니다.
> 250318 outbound_approve.sql 프로시저 변경입니다.

- src/MySql/inventory_read_by_clientID.sql
- src/controller/WarehouseControllerImpl.java
- src/domain/Inventory/controller/InventoryIntegratedController.java
- src/domain/Inventory/controller/InventoryReadController.java
- src/domain/Inventory/controller/InventoryReadControllerImp.java
- src/domain/Inventory/repository/InventoryReadRepoImp.java
- src/domain/Inventory/service/InventoryReadServiceImp.java
> 재고 read_by_clientID 생성자 오버로딩(관리자, 회원), 파라미터 수정

- src/common/Text.java
- src/config/Diconfig.java
- src/controller/WarehouseControllerImpl.java
- src/domain/Outbound/controller/OutboundAdminControllerImpl.java
- src/domain/Outbound/controller/OutboundController.java
- src/domain/Outbound/repository/OutboundAdminRepositoryImpl.java
250318 outbound_admin_controller enum변경입니다.
> 250318 outbound_admin_controller enum변경입니다.

- src/MySql/inventory_readAll_procedure.sql
- src/MySql/inventory_readOne_productName.sql
- src/MySql/inventory_read_by_category.sql
- src/MySql/inventory_read_by_clientID.sql
- src/domain/Inventory/repository/InventoryReadRepoImp.java
> 재고 프로시저 수정

- src/config/Diconfig.java
- src/controller/WarehouseControllerImpl.java
- src/domain/Inbound/controller/InboundCheckControllerImp.java
- src/domain/Inbound/controller/InboundController.java
- src/domain/Inbound/controller/InboundDeleteController.java
- src/domain/Inbound/controller/InboundDeleteControllerImp.java
- src/domain/Inbound/controller/InboundSearchController.java
- src/domain/Inbound/controller/InboundSearchControllerImp.java
- src/domain/Inbound/repository/InboundDeleteRepo.java
- src/domain/Inbound/repository/InboundDeleteRepoImp.java
- src/domain/Inbound/repository/InboundSearchRepo.java
- src/domain/Inbound/repository/InboundSearchRepoImp.java
- src/domain/Inbound/service/InboundCheckService.java
- src/domain/Inbound/service/InboundCheckServiceImp.java
- src/domain/Inbound/service/InboundDeleteService.java
- src/domain/Inbound/service/InboundDeleteServiceImp.java
- src/domain/Inbound/service/InboundSearchService.java
- src/domain/Inbound/service/InboundSearchServiceImp.java
> 인바운드 컨트롤러테스트진행

- src/MySql/outbound_approve.sql
250318 출고요청 관리자 승인시
출고 status = 1(승인)
ware_id = null일 경우
ware_id = 'ware1'으로 변경되도록 프로시저 수정하였습니다.
> 250318 출고요청 관리자 승인시 창고 배정하도록 프로시저 수정하였습니다.

- src/MySql/outbound_delete.sql
- src/MySql/outbound_user_get_request.sql
- src/MySql/outbound_user_read.sql
- src/controller/WarehouseControllerImpl.java
- src/domain/Outbound/controller/OutboundController.java
- src/domain/Outbound/controller/OutboundUserController.java
- src/domain/Outbound/controller/OutboundUserControllerImpl.java
- src/domain/Outbound/repository/OutboundUserRepository.java
- src/domain/Outbound/repository/OutboundUserRepositoryImpl.java
- src/domain/Outbound/service/OutboundUserService.java
- src/domain/Outbound/service/OutboundUserServiceImpl.java
> 출고 요청 기능 제작

- src/MySql/signUp.sql
- src/domain/AccountManagement/User/controller/SignUpControllerImpl.java
- src/domain/AccountManagement/User/repository/UserLoginRepositoryImpl.java
user 비밀번호 salt / sha256 방식 암호화
로그인 시 ":" 스플릿 해서 비교하여 같으면 로그인!
uuid 10자리 변경
> user uuid / 비밀번호 암호화 / 로그인시 입력된 비밀번호와 암호화된 비밀번호 비교 후 로그인 

- src/config/Diconfig.java
- src/domain/Inbound/controller/InboundCheckControllerImp.java
- src/domain/Inbound/controller/InboundController.java
- src/domain/Inbound/controller/InboundInsertController.java
- src/domain/Inbound/controller/InboundInsertControllerImp.java
- src/domain/Inbound/controller/InboundSearchControllerImp.java
- src/domain/Inbound/repository/InboundCheckRepoImp.java
- src/domain/Inbound/repository/InboundInsertRepo.java
- src/domain/Inbound/repository/InboundInsertRepoImp.java
- src/domain/Inbound/repository/InboundSearchRepoImp.java
- src/domain/Inbound/service/InboundCheckService.java
- src/domain/Inbound/service/InboundCheckServiceImp.java
- src/domain/Inbound/service/InboundInsertService.java
- src/domain/Inbound/service/InboundInsertServiceImp.java
> 인바운드 인서트 및 컨트롤러 수정

- src/MySql/outbound_approve.sql
- src/MySql/userApprove.sql
- src/common/Text.java
- src/domain/AccountManagement/Admin/controller/UserManagementControllerImpl.java
- src/domain/AccountManagement/Admin/repository/LoginRepositoryImpl.java
- src/domain/AccountManagement/Admin/repository/UserManagementRepositoryImpl.java
- src/domain/Outbound/controller/OutboundAdminControllerImpl.java
- src/domain/Outbound/repository/OutboundAdminRepositoryImpl.java
1. 재고 테이블 최종 출고일에 now찍기(출고) -> 완료
2. 회원관리 연락처 양식 통일 -> REGEX 변경완료
3.업체별 or 출고ID 개별 승인시 미승인 리스트 출력기능 넣었고,
미승인 리스트가 0건이면 상위 메뉴 반환되게 하였습니다.
> 250319 테스트시 에러 발견 사항 수정입니다.

- src/MySql/inventory_readAll_procedure.sql
- src/MySql/inventory_readOne_productName.sql
- src/MySql/inventory_read_by_category.sql
- src/MySql/inventory_read_by_clientID.sql
- src/MySql/userApprove.sql
- src/config/Diconfig.java
- src/domain/Inventory/controller/InventoryDeleteControllerImp.java
- src/domain/Inventory/controller/InventoryIntegratedController.java
- src/domain/Inventory/controller/InventoryReadControllerImp.java
- src/domain/Inventory/controller/InventoryUpdateControllerImp.java
- src/domain/Inventory/repository/InventoryDeleteRepoImp.java
- src/domain/Inventory/repository/InventoryReadRepo.java
- src/domain/Inventory/repository/InventoryReadRepoImp.java
- src/domain/Inventory/repository/InventoryUpdateRepoImp.java
- src/domain/Inventory/service/InventoryDeleteServiceImp.java
- src/domain/Inventory/service/InventoryReadServiceImp.java
- src/domain/Inventory/service/InventoryUpdateServiceImp.java
1차 테스트 후 엑셀에 있는 수정 사항 반영해서 수정했습니다
> 1차 통합 테스트 후 재고 수정

- src/MySql/Inbound_search.sql
- src/MySql/inbound_check.sql
- src/controller/WarehouseControllerImpl.java
- src/domain/Inbound/controller/InboundCheckController.java
- src/domain/Inbound/controller/InboundCheckControllerImp.java
- src/domain/Inbound/controller/InboundController.java
- src/domain/Inbound/controller/InboundDeleteControllerImp.java
- src/domain/Inbound/controller/InboundInsertControllerImp.java
- src/domain/Inbound/controller/InboundSearchControllerImp.java
- src/domain/Inbound/repository/InboundCheckRepoImp.java
- src/domain/Inbound/repository/InboundDeleteRepoImp.java
- src/domain/Inbound/repository/InboundInsertRepo.java
- src/domain/Inbound/repository/InboundInsertRepoImp.java
- src/domain/Inbound/repository/InboundSearchRepo.java
- src/domain/Inbound/repository/InboundSearchRepoImp.java
- src/domain/Inbound/service/InboundSearchService.java
- src/domain/Inbound/service/InboundSearchServiceImp.java
- src/dto/ClientUpdateDto.java
> 인바운드 통합테스트 후 수정

- src/MySql/User/inbound_delete.sql
- src/MySql/inbound_check.sql
- src/domain/AccountManagement/Admin/controller/UserManagementControllerImpl.java
- src/domain/Inbound/repository/InboundCheckRepo.java
- src/domain/Inbound/repository/InboundCheckRepoImp.java
- src/domain/Inbound/repository/InboundDeleteRepoImp.java
- src/domain/Inbound/repository/InboundSearchRepoImp.java
> Fix inbound number >id

- src/config/Diconfig.java
- src/domain/Inbound/controller/InboundCheckController.java
- src/domain/Inbound/controller/InboundCheckControllerImp.java
- src/domain/Inbound/controller/InboundController.java
- src/domain/Inbound/controller/InboundDeleteController.java
- src/domain/Inbound/controller/InboundDeleteControllerImp.java
- src/domain/Inbound/controller/InboundInsertController.java
- src/domain/Inbound/controller/InboundInsertControllerImp.java
- src/domain/Inbound/controller/InboundSearchController.java
- src/domain/Inbound/controller/InboundSearchControllerImp.java
- src/domain/Inbound/repository/InboundCheckRepo.java
- src/domain/Inbound/repository/InboundDeleteRepo.java
- src/domain/Inbound/repository/InboundDeleteRepoImp.java
- src/domain/Inbound/repository/InboundInsertRepo.java
- src/domain/Inbound/repository/InboundInsertRepoImp.java
- src/domain/Inbound/repository/InboundSearchRepo.java
- src/domain/Inbound/repository/InboundSearchRepoImp.java
- src/domain/Inbound/service/InboundCheckService.java
- src/domain/Inbound/service/InboundCheckServiceImp.java
- src/domain/Inbound/service/InboundDeleteService.java
- src/domain/Inbound/service/InboundDeleteServiceImp.java
- src/domain/Inbound/service/InboundInsertService.java
- src/domain/Inbound/service/InboundInsertServiceImp.java
- src/domain/Inbound/service/InboundSearchService.java
- src/domain/Inbound/service/InboundSearchServiceImp.java
> 인바운드 자바독 입력

- src/domain/Inventory/controller/InventoryDeleteController.java
- src/domain/Inventory/controller/InventoryDeleteControllerImp.java
- src/domain/Inventory/controller/InventoryIntegratedController.java
- src/domain/Inventory/controller/InventoryReadController.java
- src/domain/Inventory/controller/InventoryReadControllerImp.java
- src/domain/Inventory/controller/InventoryUpdateControllerImp.java
- src/domain/Inventory/repository/InventoryDeleteRepo.java
- src/domain/Inventory/repository/InventoryDeleteRepoImp.java
- src/domain/Inventory/repository/InventoryReadRepoImp.java
- src/domain/Inventory/repository/InventoryUpdateRepoImp.java
- src/domain/Inventory/service/InventoryDeleteServiceImp.java
- src/domain/Inventory/service/InventoryReadServiceImp.java
- src/domain/Inventory/service/InventoryUpdateServiceImp.java
- src/dto/InventoryDto.java
> 재고 Javadoc 작성

- src/domain/AccountManagement/User/controller/ProductControllerImpl.java
250320 상품등록 카테고리 switch 변경하였습니다.
> 250320 상품등록 카테고리 switch 변경하였습니다.

- src/domain/Inbound/controller/InboundCheckControllerImp.java
- src/domain/Inbound/repository/InboundCheckRepoImp.java
> 인바운드 체크 사용안하는 메서드 삭제
